[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "@layerzerolabs/solidity-examples=lib/solidity-examples",
  "@pythnetwork/pyth-sdk-solidity/=lib/pyth-sdk-solidity"
  ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
